add_files -norecurse -scan_for_includes $SRC_AXI_NODE
add_files -norecurse -scan_for_includes $SRC_APB_NODE
add_files -norecurse -scan_for_includes $SRC_AXI_MEM_IF_DP
add_files -norecurse -scan_for_includes $SRC_AXI_SPI_SLAVE
add_files -norecurse -scan_for_includes $SRC_AXI_SPI_MASTER
add_files -norecurse -scan_for_includes $SRC_APB_UART_SV
add_files -norecurse -scan_for_includes $SRC_APB_GPIO
add_files -norecurse -scan_for_includes $SRC_APB_EVENT_UNIT
add_files -norecurse -scan_for_includes $SRC_APB_SPI_MASTER
add_files -norecurse -scan_for_includes $SRC_FPU
add_files -norecurse -scan_for_includes $SRC_APB_PULPINO
add_files -norecurse -scan_for_includes $SRC_APB_FLL_IF
add_files -norecurse -scan_for_includes $SRC_CORE2AXI
add_files -norecurse -scan_for_includes $SRC_APB_TIMER
add_files -norecurse -scan_for_includes $SRC_AXI2APB
add_files -norecurse -scan_for_includes $SRC_APB_I2C
add_files -norecurse -scan_for_includes $SRC_ZERORISCY_REGFILE_FPGA
add_files -norecurse -scan_for_includes $SRC_ZERORISCY
add_files -norecurse -scan_for_includes $SRC_AXI_SLICE_DC
add_files -norecurse -scan_for_includes $SRC_RISCV
add_files -norecurse -scan_for_includes $SRC_RISCV_REGFILE_FPGA
add_files -norecurse -scan_for_includes $SRC_APB_UART
add_files -norecurse -scan_for_includes $SRC_AXI_SLICE
add_files -norecurse -scan_for_includes $SRC_APB_AES
add_files -norecurse -scan_for_includes $SRC_ADV_DBG_IF
add_files -norecurse -scan_for_includes $SRC_APB2PER
